### PR TITLE
Bypass summary printing if any of the group is pass-fail

### LINKED ISSUE #231: Using the "pass-fail" `--groupby` option has reduntant summary output
When grouping the output by `pass-fail` the `Summary: x succeeded, x failed` section seems redundant since the output is already grouped by passing/fail. When grouping by pass-fail, the summary for each section should be excluded.

```
/test # cd /test && /validator --groupby=pass-fail
Passed
    ✓ /test/fixtures/exclude-file-types/excluded.json
    ✓ /test/fixtures/exclude-file-types/not-excluded.toml
    ✓ /test/fixtures/good.csv
    ✓ /test/fixtures/good.editorconfig
    ✓ /test/fixtures/good.env
    ✓ /test/fixtures/good.hcl
    ✓ /test/fixtures/good.hocon
    ✓ /test/fixtures/good.ini
    ✓ /test/fixtures/good.json
    ✓ /test/fixtures/good.plist
    ✓ /test/fixtures/good.properties
    ✓ /test/fixtures/good.toml
    ✓ /test/fixtures/good.yaml
    ✓ /test/fixtures/mixedcase-extension/good.CSv
    ✓ /test/fixtures/mixedcase-extension/good.HCl
    ✓ /test/fixtures/mixedcase-extension/good.INi
    ✓ /test/fixtures/mixedcase-extension/good.JSon
    ✓ /test/fixtures/mixedcase-extension/good.PList
    ✓ /test/fixtures/mixedcase-extension/good.PRoperties
    ✓ /test/fixtures/mixedcase-extension/good.TOml
    ✓ /test/fixtures/mixedcase-extension/good.YAml
    ✓ /test/fixtures/subdir/good.json
    ✓ /test/fixtures/subdir2/good.ini
    ✓ /test/fixtures/subdir2/good.json
    ✓ /test/fixtures/uppercase-extension/good.CSV
    ✓ /test/fixtures/uppercase-extension/good.HCL
    ✓ /test/fixtures/uppercase-extension/good.INI
    ✓ /test/fixtures/uppercase-extension/good.JSON
    ✓ /test/fixtures/uppercase-extension/good.PLIST
    ✓ /test/fixtures/uppercase-extension/good.PROPERTIES
    ✓ /test/fixtures/uppercase-extension/good.TOML
    ✓ /test/fixtures/uppercase-extension/good.YAML
    ✓ /test/fixtures/with-depth/additional-depth/sample.json
    ✓ /test/fixtures/with-depth/sample.json
    ✓ /test/output/example/good.json
    ✓ /test/output/example/result.json
    ✓ /test/output/example/result.xml

Summary: 37 succeeded, 0 failed

Failed
    × /test/fixtures/subdir/bad.json
        error: Error at line 3 column 14: invalid character ':' after array element
    × /test/fixtures/subdir/bad.toml
        error: Error at line 6 column 6: toml: expected character =
    × /test/fixtures/subdir/bad.yml
        error: yaml: line 3: did not find expected '-' indicator
    × /test/fixtures/subdir2/bad.csv
        error: parse error on line 1, column 20: bare " in non-quoted-field
    × /test/fixtures/subdir2/bad.editorconfig
        error: cannot load ini file: unclosed section: [*.md
    × /test/fixtures/subdir2/bad.env
        error: Error at line 2: invalid escape sequence: "a"
    × /test/fixtures/subdir2/bad.hcl
        error: error at line 1 column 1: :1,1-2: Invalid argument name; Argument names must not be quoted.
    × /test/fixtures/subdir2/bad.hocon
        error: two adjacent commas at: 3:16, adjacent commas in arrays and objects are invalid!
    × /test/fixtures/subdir2/bad.ini
        error: key-value delimiter not found: name value
    × /test/fixtures/subdir2/bad.json
        error: Error at line 1 column 3: invalid character '}' looking for beginning of value
    × /test/fixtures/subdir2/bad.plist
        error: plist: error parsing XML property list: missing value in dictionary
    × /test/fixtures/subdir2/bad.properties
        error: circular reference in:
               key=${key}

Summary: 0 succeeded, 12 failed

Total Summary: 37 succeeded, 12 failed
```

### PR DESCRIPTION
**Pull request by siddharthkoli**
This PR removes the summary printing when `--groupby` flag contains `pass-fail` as one of the groups. Summary is only printed if `pass-fail` is absent.

Fixes #231

### CODE REVIEW

File: pkg/reporter/stdout_reporter.go [hunk 1]
```diff
@@ -94,7 +98,9 @@ func PrintTripleGroupStdout(groupReport map[string]map[string]map[string][]Repor
 				totalSuccessCount += stdoutReport.Summary.Passed
 				totalFailureCount += stdoutReport.Summary.Failed
 				fmt.Println(stdoutReport.Text)
-				fmt.Printf("        Summary: %d succeeded, %d failed\n\n", stdoutReport.Summary.Passed, stdoutReport.Summary.Failed)
+				if groupOne != "Passed" && groupOne != "Failed" && groupTwo != "Passed" && groupTwo != "Failed" && groupThree != "Passed" && groupThree != "Failed" {
+					fmt.Printf("        Summary: %d succeeded, %d failed\n\n", stdoutReport.Summary.Passed, stdoutReport.Summary.Failed)
+				}
```
Comment (ccoVeille) [inline pkg/reporter/stdout_reporter.go:103]: I would suggest you to create a method like this

```go
func checkGroup(groups ...string) {

	for , group := range groups {
		if group == "Passed" || group == "Failed" {
			return false
		}
	}

	return true
}
```

Then here, (and for the other checks), you can call


```suggestion
				if checkGroup(groupOne, groupTwo, groupThree) {
					fmt.Printf("        Summary: %d succeeded, %d failed\n\n", stdoutReport.Summary.Passed, stdoutReport.Summary.Failed)
				}
```

Comment (siddharthkoli) [reply pkg/reporter/stdout_reporter.go]: Thanks for the feedback!

Comment (ccoVeille) [reply pkg/reporter/stdout_reporter.go]: Adding a Co-authored-by tag to your commit would be appreciated then

```
Co-authored-by: ccoVeille <3875889+ccoVeille@users.noreply.github.com>
```

https://docs.github.com/articles/creating-a-commit-with-multiple-authors

Comment (siddharthkoli) [reply pkg/reporter/stdout_reporter.go]: Added the tag 👍

**Review by ccoVeille — APPROVED** [review]

**Review by kehoecj — APPROVED** [review]
LGTM, thanks for the PR @siddharthkoli !
