### PR TITLE
Fix: yml is valid type

### LINKED ISSUE #205: Cannot exclude type yml from file list
`validator --exclude-file-types=yml` raises throws an error that it's an invalid file type

### PR DESCRIPTION
**Pull request by gurukiran07**
Closes #205 

Make searching for extensions considering all the possible extensions from `FileType.Extensions` instead of `FileType.Name`

Testing: 
image

### CODE REVIEW

**Review by mohizzzol — APPROVED** [review]

**Review by ccoVeille — APPROVED** [review]

File: cmd/validator/validator.go [hunk 1]
```diff
@@ -84,7 +86,7 @@ func validateFileTypeList(input []string) bool {
 		if len(t) == 0 {
 			continue
 		}
-		if !slices.Contains(types, t) {
+		if !slices.Contains(types, strings.ToLower(t)) {
```
Comment (ccoVeille) [inline cmd/validator/validator.go:89]: You will have to make sure the method that add the types convert to lowercase before adding to the slice types

**Review by ccoVeille — APPROVED** [review]

**Comment by mohizzzol** [comment]
merge it...

**Review by kehoecj — APPROVED** [review]
LGTM! Thanks for the PR @gurukiran07
